src/components/visualizations/dts/dts.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5211
* https://federal-spending-transparency.atlassian.net/browse/DA-5210
These two tickets go hand in hand and are quick to check. 
Check these categories :
* NASA, NASA Programs
* Veterans Affairs programs, Dept of Veterans Affairs ( VA )
* Veteran Benefits (EFT), VA Benefits
You should see the new footnote reflected as well as the dotted lines representing older data.
It should look the same as `Supple Nutrition Assist Program (SNAP)` category.

DTS Updates to categories/footnotes

---

src/components/visualizations/dendro/dendro.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5293

fix dendro icon from moving around

---

src/components/visualizations/mapbox/mapbox.jsx
src/components/visualizations/mapbox/mapbox.scss
src/page-sections/colleges-and-universities/institutions.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5140
format map tooltips
This is my best effort. Let me know if you see anything different enough to call out.
Sorry my lint rules aggressively "clean up" CSS files...

5140 fix map tip spacing

---

src/page-sections/colleges-and-universities/institutions.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5764
align map icon in left panel

use MUI icon instead of img

---

src/components/visualizations/investment-overview/investment.scss
src/components/visualizations/investment-overview/overview.js

style GI Bill hyper link in sec1 according to https://federal-spending-transparency.atlassian.net/browse/DA-5130

explicitly specify CSS to override global

---

src/page-sections/colleges-and-universities/institutions.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5725
just had to redo the grid so everything's on the same vertical

5725 align cu map details

---

src/components/table/data-table.jsx
src/components/visualizations/mapbox/mapbox.jsx
src/page-sections/colleges-and-universities/agencies/agencies-table-container.jsx
src/page-sections/colleges-and-universities/categories/categories-table-container.jsx
src/page-sections/colleges-and-universities/institutions.jsx

toggle map data table
https://federal-spending-transparency.atlassian.net/browse/DA-5765
just adds "display" prop to DataTable and Map viz to hide on demand (everything else is auto code cleanup)

5765 toggle map & table

---

src/page-sections/colleges-and-universities/categories/categories.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-5498
https://federal-spending-transparency.atlassian.net/browse/DA-5830
adjust vertical space of sunburst download

fix sunburst container heights

---

src/pages/colleges-and-universities/methodologies.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5594
fix 1,2,4 in ticket, another created for #3, so this is just copy edits (and code formatting)

wip fix 1 2 4

---

src/page-sections/colleges-and-universities/categories/categories.jsx

Jira Ticket - https://federal-spending-transparency.atlassian.net/browse/DA-5384

Added spacing between cu sunburst radio buttons

---

src/components/visualizations/dendro/dendro.jsx
src/containers/fed-acct/fed-acct-container.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5390

Dendro ie render fix

---

src/pages/homelessness-analysis/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5771
A lot of notes, but really it's just the AC and done that we need to be concerned with.

Changed the word "which" to "what".

---

.idea/codeStyles/Project.xml
src/components/visualizations/homelessness-analysis/treemap/treemap.jsx
src/components/visualizations/homelessness-analysis/treemap/treemap.scss

https://federal-spending-transparency.atlassian.net/browse/DA-5484
Please and thank you

Da5484 homelessness coc panel

---

src/containers/budget-function/budget-function-container.jsx
src/pages/americas-finance-guide/revenue-and-gdp/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5785
The csv file for the data changes depending on what year the user selects on the radio buttons.
Note - Also removed some html on Revenue and GDP in AFG. You don't need to test this at this time.

Da5785 budget function download

---

src/components/visualizations/dts/dts.jsx
src/components/visualizations/dts/dts.scss
src/pages/dts/index.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5459

dts responsiveness fixes 1-1 prod

---

src/page-sections/colleges-and-universities/categories/sunburst-container/sunburst-container.jsx

add "top 5" to sunburst detail panels when appropriate
https://federal-spending-transparency.atlassian.net/browse/DA-5839
To test, just click the first 3 outer sectors. First shows (top 5) on both, second shows on one, third shows on neither

change detection condition

---

src/libs/ffg/src/globalSass/trends/trendControls.scss

https://federal-spending-transparency.atlassian.net/browse/DA-5791

Spending trends cursor

---

src/components/section-elements/downloads/downloads.jsx
src/components/section-elements/downloads/downloads.module.scss

add underline on hover to download
https://federal-spending-transparency.atlassian.net/browse/DA-5772
actual change is only in the scss file, the other was code cleanup while I found where to make the change

add underline on hover

---

src/components/footers/site.module.scss

fix site footer colors and font size
https://federal-spending-transparency.atlassian.net/browse/DA-5277
should appear identical on all pages

fix site footer format

---

src/page-sections/home/dts-tile/dts-tile.jsx
src/utils/number-formatter.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5715
fix value suffix on DTS home page tile
consequence: add a new number-formatter output option

5715 fix dts metric postfix

---

src/components/hwcta-link/hwcta-link.jsx
src/components/hwcta-link/hwcta-link.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-5267

reconsider layout of hwcta link

---

src/page-sections/analyst-guide/agency-related.jsx
src/page-sections/analyst-guide/classifications.jsx
src/page-sections/analyst-guide/federal-account-data.jsx
src/page-sections/analyst-guide/general-questions.jsx
src/pages/analyst-guide/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5360

5360 correct analyst guide

---

src/components/visualizations/homelessness-analysis/mapviz/mapviz.jsx
src/page-sections/homelessness-analysis/geography.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5739

Homelessness download component

---

src/components/visualizations/homelessness-analysis/mapviz/mapviz.jsx
src/components/visualizations/homelessness-analysis/treemap/treemap.jsx
src/page-sections/homelessness-analysis/federal-programs.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5806
A simpler fix than I thought! Quick and easy!

toc duplicates fix 

---

src/components/table/paginator.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5722
I only wish finding the solution was as simple as the amount of code this took.

Da5722 paginator fix

---

src/components/hwcta-link/hwcta-link.jsx
src/components/hwcta-link/hwcta-link.module.scss

* https://federal-spending-transparency.atlassian.net/browse/DA-5806
This is super quick, one line fixer. (^:

super quick add underline to hwcta

---

src/page-sections/colleges-and-universities/institutions.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5811

C&U Section 2 download

---

src/components/visualizations/dts/dts.jsx
src/page-sections/home/dts-tile/landing-dts.scss
src/pages/homelessness-analysis/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5829
Also made a tiny copy change on homelessness analysis.

Da5829 dts categories issue

---

src/components/headers/headers.jsx
src/components/hwcta/hwcta.jsx
src/pages/dts/methodologies.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5872
sorry, accidentally also includes https://federal-spending-transparency.atlassian.net/browse/DA-5870

fix dts dsm title, add dsm header

---

src/pages/federal-employees/index.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5464
Just a quick newline add to match the copy pictures

update copy fed section 3 newline

---

src/components/visualizations/sankey/sankey.jsx
src/containers/budget-function/budget-function-container.jsx
src/pages/budget-function/index.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5113
Added Reset Button and Share to `Budget Function` page

add reset button and share button to budget function

---

src/components/layouts/default/default.jsx
src/components/layouts/header-only/header-only.jsx
src/pages/budget-function/index.jsx
src/pages/colleges-and-universities/index.jsx
src/pages/competition-in-contracting/index.jsx
src/pages/contract-explorer/index.jsx
src/pages/dts/index.jsx
src/pages/federal-account-explorer/index.jsx
src/pages/federal-employees/index.jsx
src/pages/homelessness-analysis/index.jsx
src/pages/index.jsx

Jira Ticket - https://federal-spending-transparency.atlassian.net/browse/DA-5204
NOTE - I double checked and knowledge graph info was already done for AFG

Knowledge Graph

---

src/components/headers/mobile-menu.jsx
src/components/headers/page-mobile.scss
src/components/headers/page.jsx
src/components/headers/page.module.scss

* https://federal-spending-transparency.atlassian.net/browse/DA-5905
* https://federal-spending-transparency.atlassian.net/browse/DA-4876
* https://federal-spending-transparency.atlassian.net/browse/DA-4875
Clicking caret working now on mobile/tablet
AFG Link fix + small cleanup on things I saw that were code smells
Small style changes (pixel tweaks) on mobile hamburger icon (wasn't aligned properly)

afg broken link, caret clicking, transition

---

src/components/visualizations/dts/dts.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5874
just re-fixing the chart dates

reimplement date fix

---

src/components/headers/mobile-menu.jsx
src/components/headers/page.jsx
src/components/headers/page.module.scss

Just an addition to https://federal-spending-transparency.atlassian.net/browse/DA-4876 to handle the things that @anjenkin pointed out

refactor hamburger click

---

src/components/visualizations/homelessness-analysis/mapviz/mapviz.jsx
src/page-sections/homelessness-analysis/geography.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5879
Adding reset to map viz

homelessness reset fix

---

src/components/glossary/glossary.jsx
src/components/headers/mobile-menu.jsx
src/components/headers/page.jsx
src/components/headers/page.module.scss

JIRA Ticket - https://federal-spending-transparency.atlassian.net/browse/DA-5876

show glossary on click of mobile menu item

---

gatsby-browser.js
gatsby-config.js
package-lock.json
package.json
src/components/headers/official-banner.jsx
src/components/more-analyses/more-analyses.jsx
src/libs/ffg/src/globalSass/cg.scss
src/page-sections/home/feature-row/feature-row.jsx
src/page-sections/home/feature-tile/feature-tile.jsx
src/page-sections/home/more-analyses-tiles/more-analyses-tiles.jsx
src/page-sections/home/resources-row/resources-row.jsx
src/page-sections/home/secondary-tile/side-by-side-layout/secondary-tile.jsx
src/page-sections/home/secondary-tile/stacked-layout/secondary-tile.jsx
src/pages/index.jsx
src/styles/index.scss

JIRA Ticket - https://federal-spending-transparency.atlassian.net/browse/DA-5909
Lighthouse made the following improvements that were addressed in this ticket - 
Defer offscreen images - https://web.dev/offscreen-images/?utm_source=lighthouse&utm_medium=devtools 
Ensure text remains visible during webfont load - https://web.dev/font-display/?utm_source=lighthouse&utm_medium=devtools
Not gzipping with this ticket.  It's making the build time  really long without much perf gain.

Adopt recommendations made by Lighthouse perf audit tool

---

src/components/toc/toc.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5737

added toc hover color

---

src/page-sections/colleges-and-universities/agencies/agencies.jsx
src/page-sections/colleges-and-universities/categories/categories.jsx
src/page-sections/colleges-and-universities/institutions.jsx

JIRA Ticket - https://federal-spending-transparency.atlassian.net/browse/DA-5916

Re-connected C & U Table Search

---

src/components/headers/page.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6038

checked prop before setting state

---

src/page-sections/colleges-and-universities/institutions.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5938
Another quick one. Just had to add the `<Hidden/>` component back in to the `Institutions` section. 
🏀

cu searchbox fix for mobile

---

src/components/headers/page-mobile.scss
src/components/layouts/home/home.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-6049
actually, just fixing space between menu & home page generally

mobile spacing adjustment

---

src/components/afg-nav/afg-nav.jsx
src/components/headers/dropdown.jsx
src/components/headers/genericHeader.jsx
src/components/headers/mobile-menu.jsx
src/components/headers/official-banner.jsx
src/components/headers/page.jsx
src/components/hwcta-link/hwcta-link.jsx
src/components/hwcta/hwcta.jsx
src/page-sections/home/resources-row/resources-row.jsx
src/page-sections/home/secondary-tile/stacked-layout/secondary-tile.jsx
src/pages/404.js
src/pages/americas-finance-guide/debt/analysis/index.jsx
src/pages/americas-finance-guide/debt/country-comparison/index.jsx
src/pages/americas-finance-guide/debt/index.jsx
src/pages/americas-finance-guide/debt/trends/index.jsx
src/pages/americas-finance-guide/deficit/country-comparison/index.jsx
src/pages/americas-finance-guide/deficit/index.jsx
src/pages/americas-finance-guide/deficit/trends/index.jsx
src/pages/americas-finance-guide/index.jsx
src/pages/americas-finance-guide/revenue/categories/index.jsx
src/pages/americas-finance-guide/revenue/country-comparison/index.jsx
src/pages/americas-finance-guide/revenue/index.jsx
src/pages/americas-finance-guide/revenue/trends/index.jsx
src/pages/americas-finance-guide/spending/categories/index.jsx
src/pages/americas-finance-guide/spending/country-comparison/index.jsx
src/pages/americas-finance-guide/spending/index.jsx
src/pages/americas-finance-guide/spending/trends/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6034
Fixes some weird behavior across the same.

Convert a tags to Gatsby Links

---

src/pages/homelessness-analysis/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5977

added missing text to homelessness page, section 3

---

src/containers/budget-function/budget-function-container.jsx
src/containers/contract-explorer/contract-explorer-container.jsx
src/containers/fed-acct/fed-acct-container.jsx
src/page-sections/colleges-and-universities/agencies/agencies.jsx
src/page-sections/colleges-and-universities/categories/categories.jsx
src/page-sections/colleges-and-universities/institutions.jsx
src/page-sections/homelessness-analysis/federal-programs.jsx
src/page-sections/homelessness-analysis/geography.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5937
The following changes are listed in the ticket - just check me on a couple of pages, please!

download date fixes

---

src/components/afg-nav/afg-nav.jsx
src/pages/americas-finance-guide/debt/analysis/index.jsx
src/pages/americas-finance-guide/debt/index.jsx
src/pages/americas-finance-guide/debt/trends/index.jsx
src/pages/americas-finance-guide/deficit/index.jsx
src/pages/americas-finance-guide/deficit/trends/index.jsx
src/pages/americas-finance-guide/revenue/categories/index.jsx
src/pages/americas-finance-guide/revenue/index.jsx
src/pages/americas-finance-guide/revenue/trends/index.jsx
src/pages/americas-finance-guide/spending/categories/index.jsx
src/pages/americas-finance-guide/spending/index.jsx
src/pages/americas-finance-guide/spending/trends/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6059
To test, try to reproduce the issue on the initial page load and then after refreshing the page.

Hardcode fa svg width

---

src/components/hwcta-link/hwcta-link.jsx
src/components/section-elements/downloads/downloads.jsx

Added width to the download button and ds&m arrow
https://federal-spending-transparency.atlassian.net/browse/DA-6059

added width to download button and ds&m arrow

---

src/components/hwcta/hwcta.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6041

Fix DS&M back button

---

src/components/visualizations/homelessness-analysis/treemap/treemap.scss

https://federal-spending-transparency.atlassian.net/browse/DA-6047

increased line height on mobile

---

src/components/visualizations/sankey/sankey.jsx
src/components/visualizations/sankey/sankey.scss
src/containers/budget-function/budget-function-container.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6006

Re-align Budget Function Sankey for IE 11

---

src/components/afg-nav/afg-nav.jsx
src/pages/americas-finance-guide/spending/trends/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6077

fixed highlighting on afg nav bar

---

src/components/visualizations/homelessness-analysis/mapviz/mapviz.jsx
src/page-sections/homelessness-analysis/federal-programs.jsx

oops, I fixed a couple of styles that Matthew actually had correct...

reverting to correct styles

---

src/libs/ffg/src/revenue/intro/revenue-intro.scss
src/pages/americas-finance-guide/debt/country-comparison/index.jsx
src/pages/americas-finance-guide/deficit/country-comparison/index.jsx
src/pages/americas-finance-guide/index.jsx
src/pages/americas-finance-guide/revenue/categories/index.jsx
src/pages/americas-finance-guide/revenue/country-comparison/index.jsx
src/pages/americas-finance-guide/revenue/index.jsx
src/pages/americas-finance-guide/spending/country-comparison/index.jsx
src/pages/americas-finance-guide/spending/index.jsx

Fixed modal position for misalignment issues noted in this ticket - https://federal-spending-transparency.atlassian.net/browse/DA-6103
- Flxed broken links
- Added width to several font awesome icons
Close icons were fixed in a previous PR

Afg Modal Position

---

src/components/footers/page.jsx
src/components/footers/site.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-6131
* https://federal-spending-transparency.atlassian.net/browse/DA-6129
2 super super quick ones. Copy updates + Links.

footer link fixies

---

src/components/footers/site.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-6131
super quick, good catch

mobile footer fix

---

src/page-sections/homelessness-analysis/geography.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6174

fixed typo in homelessness data download

---

src/components/footers/site.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-5798

add hover underlines to site footer

---

src/components/more-analyses/more-analyses.jsx
src/components/more-analyses/more-analyses.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-6078

fix more analyses spacing & alignment

---

src/pages/federal-account-explorer/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5719

add missing paragraph to fed acct exp

---

src/components/tabs/tabs.jsx
src/pages/americas-finance-guide/deficit/index.jsx
src/pages/americas-finance-guide/deficit/trends/index.jsx
webpack.config.js

* https://federal-spending-transparency.atlassian.net/browse/DA-6099
Please do a `build` and `serve` to test.

Deficit afg tabs

---

src/page-sections/analyst-guide/contract-awards.jsx
src/page-sections/analyst-guide/loan-related.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6062

update analyst guide copy

---

src/pages/rd-in-contracting/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5347

remove resets from page

---

src/pages/colleges-and-universities/cu.module.scss
src/pages/colleges-and-universities/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6084

Change the style for the C & U header on mobile and tablet

---

src/components/visualizations/homelessness-analysis/mapviz/mapviz.jsx
src/page-sections/homelessness-analysis/federal-programs.jsx
src/page-sections/homelessness-analysis/geography.jsx
src/utils/number-formatter.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5334

Change NaN to NA in Homelessness Analysis

---

src/pages/rd-in-contracting/index.jsx
src/pages/rd-in-contracting/methodologies.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5355

add dsm text

---

src/components/visualizations/dts/dts.jsx
src/page-sections/home/dts-tile/dts-tile.jsx
src/pages/dts/index.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-6130
Just waiting on copy to finish the last part of the ticket, putting PR up now
waiting on copy changes for DS&M page regarding getting rid of blurbs about 'All Categories'.

all categories remove dropdown, remove footnote

---

src/pages/americas-finance-guide/index.jsx
src/pages/americas-finance-guide/revenue/categories/index.jsx
src/pages/americas-finance-guide/revenue/trends/index.jsx
src/pages/americas-finance-guide/spending/categories/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8255
https://federal-spending-transparency.atlassian.net/browse/DA-8350

8255 and 8350 - Text updates

---

src/page-sections/afg-spending/trends/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8286

8286 - Add DOL as default selection in Spending Trends chart

---

src/pages/americas-finance-guide/debt/country-comparison/index.jsx
src/pages/americas-finance-guide/deficit/country-comparison/index.jsx
src/pages/americas-finance-guide/revenue/country-comparison/index.jsx
src/pages/americas-finance-guide/spending/country-comparison/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8099

8099 - Added sort icon to country comparison pages

---

src/pages/about.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8357

[8357] About Us TOC covering footer

---

src/components/headers/page.jsx
src/components/headers/page.module.scss

Fix IE nav bug

---

src/components/footers/page.jsx
src/components/footers/page.module.scss
src/components/footers/site.jsx
src/components/footers/site.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8229
Please note that the column spacing has been updated in Zeplin.  Also, a screenshot of the page with the grid columns has been attached to the ticket.

8340 - Update footer for About Us release

---

src/components/footers/page.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8374

8374 - Increased mobile footer width

---

src/pages/about.jsx
src/pages/about.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8217

[8217] About Us copy changes

---

src/pages/about.jsx
src/svgs/about-us/background.svg
src/svgs/about-us/who-we-are.svg

https://federal-spending-transparency.atlassian.net/browse/DA-8379

[8379] Add SEO description/keywords and image alt text to About Us page

---

src/afg-helpers/dots/revenue-and-spending/compareManager.js
src/page-sections/afg-revenue/intro/index.jsx
src/pages/americas-finance-guide/revenue/index.jsx
src/pages/americas-finance-guide/spending/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8367

[8367] AFG Revenue/Spending - Selections maintained on browser resize

---

src/components/headers/official-banner.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-7259

7259 - Increase site header font size

---

src/afg-helpers/big-picture/scss/_header.scss
src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-7860
Overview page closed:
Overview page open:
Specific page closed:
Specific page open:

[7860] Mobile AFG Sub-nav

---

src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.module.scss
src/components/headers/page.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8421
The coloring and bolded text issues are only in the build version

[8421] Desktop AFG nav fixes

---

src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.module.scss
src/components/glossary/glossary.jsx
src/components/headers/page.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-7852

7852 - AFG subnav keyboard accessibility

---

src/components/afg-nav/afg-nav.jsx
src/components/headers/page.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-7862
* Just two minor tweaks.  The page loads slower in IE so the hamburger menu icon displayed really large and the subnav text displayed weird on page load.

7862 - Cross browser fixes

---

src/page-sections/analyst-guide/agency-related.jsx
src/page-sections/analyst-guide/classifications.jsx
src/page-sections/analyst-guide/contract-awards.jsx
src/page-sections/analyst-guide/federal-account-data.jsx
src/page-sections/analyst-guide/financial-assistance.jsx
src/page-sections/analyst-guide/general-questions.jsx
src/page-sections/analyst-guide/loan-related.jsx
src/pages/analyst-guide/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-7920

[7920] Update Analyst's Guide

---

src/components/headers/dropdown.jsx
src/components/headers/mobile-menu.jsx
src/components/headers/page.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8428

[8428] Change AFG nav dropdown to single link

---

src/pages/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8414

8414- Covid text update on homepage

---

src/pages/americas-finance-guide/debt/country-comparison/index.jsx
src/pages/americas-finance-guide/deficit/country-comparison/index.jsx
src/pages/americas-finance-guide/revenue/country-comparison/index.jsx
src/pages/americas-finance-guide/spending/country-comparison/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8496

8496 - Additional AFG copy updates

---

src/components/tooltip/tooltip.jsx

This is ready for review.
Somehow the code to reset the tooltip state on close was commented out.  Just uncommented that code.
https://federal-spending-transparency.atlassian.net/browse/DA-7769

7769 Fixed closing R&D tooltips

---

src/components/scrolling-circles/scrolling-circles.jsx
src/components/scrolling-circles/scrolling-circles.module.scss
src/components/section-elements/story-section/story-section.jsx
src/components/section-elements/story-section/story-section.module.scss
src/pages/federal-covid-funding/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8352
Desktop:
Tablet:
Mobile:

[8352] Scrolling TOC Circles

---

src/pages/about.jsx
src/pages/americas-finance-guide/debt/analysis/index.jsx
src/pages/americas-finance-guide/debt/country-comparison/index.jsx
src/pages/americas-finance-guide/debt/index.jsx
src/pages/americas-finance-guide/debt/trends/index.jsx
src/pages/americas-finance-guide/deficit/country-comparison/index.jsx
src/pages/americas-finance-guide/deficit/index.jsx
src/pages/americas-finance-guide/deficit/trends/index.jsx
src/pages/americas-finance-guide/index.jsx
src/pages/americas-finance-guide/revenue/categories/index.jsx
src/pages/americas-finance-guide/revenue/country-comparison/index.jsx
src/pages/americas-finance-guide/revenue/index.jsx
src/pages/americas-finance-guide/revenue/trends/index.jsx
src/pages/americas-finance-guide/spending/categories/index.jsx
src/pages/americas-finance-guide/spending/country-comparison/index.jsx
src/pages/americas-finance-guide/spending/index.jsx
src/pages/americas-finance-guide/spending/trends/index.jsx
src/pages/budget-function/index.jsx
src/pages/colleges-and-universities/index.jsx
src/pages/competition-in-contracting/index.jsx
src/pages/contract-explorer/index.jsx
src/pages/dts/index.jsx
src/pages/federal-account-explorer/index.jsx
src/pages/federal-covid-funding/index.jsx
src/pages/federal-employees/index.jsx
src/pages/homelessness-analysis/index.jsx
src/pages/index.jsx
src/pages/opioid-crisis/index.jsx
src/pages/rd-in-contracting/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8519

8519 remove keywords

---

src/components/tooltip/tooltip.jsx
src/page-sections/rd-in-contracting/categories/categories.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8536
* Also, added key to tooltip to get rid of console error

8536 - Fixed issue with tooltip not closing after tabbing out of chart

---

src/pages/americas-finance-guide/spending/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8373
this was called out by Allie in her QA review

8373 - fixed typo in spending index.jsx SEO description

---

src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.spec.js

https://federal-spending-transparency.atlassian.net/browse/DA-8466

[8466] AFG sub-nav desktop tests

---

src/components/footers/site.jsx
src/components/visualizations/dendro/dendro.jsx
src/pages/homelessness-analysis/methodologies.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8596

8596 - Fixed broken USAS links in site footer, homelessness ds&m, and federal acct explorer

---

src/page-sections/federal-covid-funding/budget/budget.module.scss
src/page-sections/federal-covid-funding/overview/overview.module.scss
src/page-sections/federal-covid-funding/tracking/tracking.module.scss
src/styles/variables.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8608

8608 - Fix section #1 body copy font weight

---

src/pages/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8610

8610 - copy changes to home page feature tile and secondary tile

---

src/pages/federal-covid-funding/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8621

8621 - added yml vars to section 3 intro blurb

---

src/page-sections/federal-covid-funding/tracking/law-summary-modal/modal.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8619

8619 - Added missing word 'for' in phase 3.5 law summary modal

---

src/pages/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8610
see Allie's comment from this morning - forgot to change the five to four in the main text when i changed it in the mobile text

8610 - changed 'five' to 'four' in main tile text

---

src/components/scrolling-circles/scrolling-circles.jsx
src/components/scrolling-circles/scrolling-circles.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8537

8537 - Fixed Intersection Observer for TOC circles nav

---

src/components/layouts/story/story.module.scss
src/components/scrolling-circles/scrolling-circles.jsx
src/components/scrolling-circles/scrolling-circles.module.scss
src/pages/federal-covid-funding/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8578

8578 toc circles mobile improvements

---

src/page-sections/federal-covid-funding/budget/budget.jsx
src/page-sections/federal-covid-funding/overview/overview.jsx
src/page-sections/federal-covid-funding/tracking/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8571

8571 - Added width and height to images on the COVID page

---

src/components/toggle/toggle.jsx
src/components/toggle/toggle.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8643

8643 - made a new css class to apply font size to toggle labels

---

src/components/toggle/toggle.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8643

8643 - added font size for phone screen size

---

src/components/toc/toc.jsx
src/components/toc/toc.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8603

8603 - added var for the rd-in-contracting color to toc component

---

src/html.js
src/styles/fonts.scss

Fixed issue found on Brian's laptop and QAT related to the path to fonts related to this ticket - 
https://federal-spending-transparency.atlassian.net/browse/DA-8569

Fix font path in html.js and font.scss

---

src/components/scroll-to-top-button/scroll-to-top-button.jsx
src/components/scrolling-circles/scrolling-circles.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8636
* Not sure why I didn't think of this before.  Guess I was thinking about listening to the scroll event and that wasn't working.

8636 - Added click event listener for scroll to top to scrolling TOC component

---

src/pages/rd-in-contracting/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-7560

7560 - added FootnoteAnchor to R&D page footnotes

---

src/components/scroll-to-top-button/scroll-to-top-button.jsx
src/components/scrolling-circles/scrolling-circles.jsx
src/components/toc/toc.jsx
src/components/toc/toc.module.scss
src/html.js
src/styles/fonts.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8537
* Fixed mobile and tablet issues found while testing DA-8537
* Also, fixed how we're detecting is mobile.  The DL breakpoints are different than AFG so we can't use the isMobileDevice helper in the AFG code.  DL has a helper checkScreenMode to determine if we're in desktop, tablet or mobile.

8537 - Fixed the mobile and tablet thresholds to determine which section is active

---

src/page-sections/federal-covid-funding/tracking/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8661

8661 - Fixed width and height for desktop phase 3 total, phase 3 loan, and tablet phase 2 and phase 3 total svgs

---

src/components/headers/dropdown.jsx
src/components/headers/genericHeader.jsx
static/sitemap.txt

https://federal-spending-transparency.atlassian.net/browse/DA-6617

6617 - added R&D in Contracting to main nav; and to the sitemap

---

src/components/layouts/story/story.jsx
src/page-sections/rd-in-contracting/categories/categories.jsx
src/pages/federal-covid-funding/index.jsx
src/pages/rd-in-contracting/index.jsx
src/pages/rd-in-contracting/rd-in-contracting.module.scss
src/styles/variables.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8546
* Please note the comment that I added to the ticket.  I also fixed the R&D page specific color used in a couple places

8546 - Added scrolling TOC circles to the R&D pag; Also fixed R&D colors

---

src/components/more-analyses/more-analyses.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-6621

6621 - Added R&D module to more analyses section

---

src/components/tooltip/tooltip.jsx
src/components/tooltip/tooltip.module.scss
src/page-sections/rd-in-contracting/categories/categories.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8666

8666 - Added fixed max width to tooltip to force text to wrap

---

src/components/more-analyses/more-analyses.spec.js

https://federal-spending-transparency.atlassian.net/browse/DA-8646

8646 - 'Fixed' more analyses unit tests

---

src/components/tooltip/tooltip.jsx
src/page-sections/rd-in-contracting/categories/categories.jsx

* When switching between desktop / tablet and tablet / mobile, the tooltip will close because we're using different svgs btw desktop, tablet and mobile.  To fix that we would have to rethink the design for this section.
https://federal-spending-transparency.atlassian.net/browse/DA-8704

8704 - Tooltip displaced after resizing the browser

---

src/components/accordion-list/accordion-list.jsx
src/components/accordion/accordion.jsx
src/components/accordion/accordion.module.scss
src/components/toc/toc.jsx
src/components/toc/toc.module.scss
src/pages/index.jsx

1. https://federal-spending-transparency.atlassian.net/browse/DA-7401
Please note, if the Coming Soon flag is on, the margin above the section name and number is greater.  Please see this Zeplin mock - https://app.zeplin.io/project/5d2f7049581d618dfb0019fe/screen/5fe34d5ead16a6a8f99d0822
2. https://federal-spending-transparency.atlassian.net/browse/DA-7562

7401 & 7562- Improve spacing above TOC and at the top of the TOC above the section number and name & R&D accordion styling

---

src/components/scrolling-circles/scrolling-circles.jsx
src/components/scrolling-circles/scrolling-circles.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8577
https://federal-spending-transparency.atlassian.net/browse/DA-8669
Both of those issues are addressed in this branch.
I reformatted the text in scrolling-circles.jsx in my IDE so it's showing the whole file as changed. Sorry about that.

8577 toc hover

---

src/page-sections/rd-in-contracting/categories/categories.jsx
src/page-sections/rd-in-contracting/spending/spending-chart.jsx
src/page-sections/rd-in-contracting/spending/spending-chart.module.scss
src/pages/index.jsx
src/pages/rd-in-contracting/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8701
The specifics about the changes are in the comments, one from Kelli and one from Heather.

8701 - rd page copy changes, as specified in the ticket

---

src/page-sections/federal-covid-funding/budget/budget.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8743

8743 - added a space in covid page section 1

---

src/components/scrolling-circles/scrolling-circles.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8723

8723 - CSS change to scrolling TOC circles to prevent overlap with vizs in R&D

---

src/components/glossary/glossary-button/glossary-button.jsx
src/components/glossary/glossary-button/glossary-button.module.scss
src/components/glossary/glossary.jsx
src/components/glossary/glossary.scss
src/components/headers/page.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8748

8748 - made the glossary button a component

---

src/components/afg-nav/afg-nav.spec.js
src/components/layouts/story/story.jsx
src/components/toc/toc.jsx
src/components/toc/toc.spec.js

https://federal-spending-transparency.atlassian.net/browse/DA-8538

8538 toc unit tests

---

src/components/image-fallback/image-fallback.jsx
src/components/image-fallback/image-fallback.module.scss
src/components/layouts/home/home.module.scss
src/page-sections/home/feature-row/feature-row.jsx
src/page-sections/home/feature-tile/feature-tile.jsx
src/page-sections/home/feature-tile/feature-tile.module.scss
src/page-sections/home/secondary-tile/stacked-layout/secondary-tile.jsx

… in the three components on the home page that used the old code
https://federal-spending-transparency.atlassian.net/browse/DA-8777

8777 image fallback component

---

src/page-sections/rd-in-contracting/categories/categories.jsx
src/page-sections/rd-in-contracting/spending/spending-chart.jsx
src/pages/rd-in-contracting/index.jsx
src/pages/rd-in-contracting/methodologies.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8738
https://federal-spending-transparency.atlassian.net/browse/DA-8768

8768/ 8738 - Misc copy updates for R & D and changes requested from NSF
