src/components/visualizations/sunburst-vega/sunburst-vega.jsx
src/containers/contract-explorer/contract-explorer-container.jsx
src/containers/contract-explorer/utils/colors.js
src/containers/contract-explorer/utils/filter.js
src/containers/contract-explorer/utils/find-by-id.js
src/containers/contract-explorer/utils/find-by-name.js
src/pages/contract-explorer/index.jsx

JIRA Ticket - https://federal-spending-transparency.atlassian.net/browse/DA-5540
* The visualization should update after selecting an item from the search (on par with prod)
* Updated the left details panels to list the top five agencies after selecting an item from search (on par with prod)
* Left the breadcrumbs available after selecting a search item to orient the user.  This is the only way for the user to determine if he has selected an agency, subagency, or contractor from the search.

Sunburst search

---

src/components/section-elements/story-section/story-section.jsx
src/components/visualizations/federal-employees/bar-chart/bar-chart.jsx
src/components/visualizations/federal-employees/bar-chart/bar-chart.module.scss
src/components/visualizations/federal-employees/mapviz/mapviz.jsx
src/components/visualizations/federal-employees/mapviz/mapviz.module.scss
src/components/visualizations/federal-employees/treemap/treemap.jsx
src/components/visualizations/federal-employees/treemap/treemap.module.scss
src/page-sections/federal-employees/who.jsx
src/pages/federal-employees/index.jsx
src/pages/federal-employees/index.module.scss

fix chart sizes in IE
https://federal-spending-transparency.atlassian.net/browse/DA-5469
IE uses different and nonsense default sizes for SVGs, so height: auto renders very small. This fix defines the containing element's height so the auto fills it.

5469 fix employees in ie

---

src/libs/ffg/src/anecdote/anecdote.scss

https://federal-spending-transparency.atlassian.net/browse/DA-5754
The 4 "Show Me" buttons on AFG overview all change the cursor to a pointer when hovering over the text and person icon, just like in prod.

Added cursor:pointer to Show Me buttons.

---

src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-5796
NOTE - Some of the landing pages on the AFG chapter will not let you select the dropdown. This is because the popup box that is seen at the top-middle of the screen has a hidden layer that covers the left and right AFG menu buttons. There is another ticket to address this: https://federal-spending-transparency.atlassian.net/browse/DA-5797

AFG mobile/tablet menu navigation

---

src/components/visualizations/dts/dts.scss

* https://federal-spending-transparency.atlassian.net/browse/DA-5752
super quick add one line of css for hover (^:

fix underline hyperlink

---

src/components/layouts/faq/faq.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5345
After poking around a bit and playing in the DOM on IE11 I have concluded that IE11 doesn't support MUI Grid `direction=column` well.
A quick change fixed this and does not alter other browsers.
https://github.com/mui-org/material-ui/issues/8854#issuecomment-340190712
Gotta love github issues (^:

fix column to row ie11 bug

---

src/pages/federal-employees/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5721
Super quick update to Federal Employees header text.

Federal Employees - Need to add "2 million" to the phrase "...employed nearly 2 million people."

---

src/containers/contract-explorer/contract-explorer-container.jsx

JIRA Ticket -https://federal-spending-transparency.atlassian.net/browse/DA-5773
This is only one part of the fix for this ticket. Fixing this part of the AC - The file with the contractor details is 38 MB!!! which is dramatically increasing our load time for the sunburst viz. Please load this file asynchronously.

Loading psc data asynchronously

---

src/components/visualizations/bubble-chart/bubble-chart.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-5726
<title> always shows as tooltip, so use aria-describedby instead. Also use actual Outreach text.

remove title tag, update aria-describedby text

---

src/components/visualizations/dts/dts.jsx
src/components/visualizations/dts/dts.scss

* https://federal-spending-transparency.atlassian.net/browse/DA-5858
Fixing the cutoff where the bar would not resize. Working as it does in `prod` now.

dts cutoff fix tablet/mobile

---

src/components/control-bar/control-bar.jsx
src/components/control-bar/control-bar.module.scss
src/components/visualizations/federal-employees/mapviz/mapviz.jsx
src/page-sections/federal-employees/what.jsx
src/page-sections/federal-employees/where.jsx
src/page-sections/federal-employees/who.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5536
Adding a prop to distinguish between pages. The `ControlBar` for the Fed Employee page just needs to always use the `25px 0` margin instead of the desktop size one for pages with the `Accordion` component that will typically fill the space.

adding prop to style fed employee page with proper spacing

---

src/page-sections/home/dts-tile/landing-dts.scss

* https://federal-spending-transparency.atlassian.net/browse/DA-6045
This is easy to test - if you are even feelin' a bit lazy and dont want to move the recent 30 file in local to test - you can edit the DOM raw on `qat` to see what im doing. Its two very small changes. (^: 
note: 22px is the default size of that in `prod` - just copied over.

dts tile spacing fix 

---

src/components/visualizations/horizontal-barchart/barchart.jsx
src/components/visualizations/sunburst/sunburst.jsx
src/page-sections/colleges-and-universities/categories/categories.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-6046
Problem with text overlapping / the whole y-axis itself wasn't displaying at all on IE11, but displays on IE11 prod.
I reverted the code one to one with how it is on prod drawing the y-axis. It seems to work as expected.
I cannot test on IE11 as `localhost` rendering has a bug right now which is being compiled into commons.js and would take a little bit to find. I am **assuming** this works, as it is a one to one port.
If we push this branch to `qat` and it doesn't do anything, i can go back to this ticket. Tested on all browsers but IE11 locally.

Barchart fixies - text overlapping/not displaying on IE11

---

src/components/visualizations/sunburst/sunburst.jsx
src/page-sections/colleges-and-universities/categories/categories.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5934
I just moved this out properly, it was in the same `div` as the sunburst and caused it to overlap when shrunk. (^:

move sunburst text so it doesn't overlap

---

src/components/headers/page.module.scss
src/pages/dts/index.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-6048
Super quick addition, needed to add footnote as we are going to be adding changes to DTS soon, post MVP.
(Also got rid of useless CSS...)

adding placeholder footnote dts

---

src/components/headers/page-mobile.scss
src/components/headers/page.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-6089
Header gets a bit weird on page load when you are in the middle of the screen. 
This is due to dynamically settings values on scroll. 
If we are past the scroll threshold, the header will load back up at the top after the dom loads.

fix header top value on load for mobile

---

src/page-sections/homelessness-analysis/federal-programs.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-6083
Map needed to be offset as layout is a bit different than prod. 
Offset by `75px` and fits the whole map nicely on a zoom out.

homelessness map realign doubleclick

---

src/styles/index.scss
src/styles/variables.scss

https://federal-spending-transparency.atlassian.net/browse/DA-6098
identified in homelessness, but actually should be site-wide

change global active link color

---

src/pages/rd-in-contracting/index.jsx

to use correct legend layout
https://federal-spending-transparency.atlassian.net/browse/DA-6196
this fixes using the mobile (stacked) layout initially, which only happened in server build

determine window size after mount

---

src/page-sections/rd-in-contracting/categories/categories.jsx
src/page-sections/rd-in-contracting/categories/categories.scss

* https://federal-spending-transparency.atlassian.net/browse/DA-6306
We put an element css selector )^:
Please try to not do this as the css gets compiled globally.
It is only safe to target an element directly if it is nested in a unique container.

get rid of css target element

---

src/components/more-analyses/more-analyses.jsx

* https://federal-spending-transparency.atlassian.net/browse/DA-5730
Add `More Analyses` component to `rd-in-contracting` page.
Order should be as ticket says: 
* Homelessness
* C&U
* Contract Explorer
* DTS

add more analyses section to rd-in-contracting

---

src/afg-helpers/big-picture/scss/_deficit-debt-heading.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8146

[8146] font styles for deficit/debt banner on overview page

---

src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-7856
After meeting again, we decided to use the mobile menu for tablets as well, so the current tablet mocks in InVision and Zeplin are inaccurate - just use the mobile ones
Overview (closed):
Overview (open):
Specific page (closed):
Specific page (open):

[7856] Tablet AFG sub-nav

---

src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-7854
sub-nav should be sticky all the time on tablet/mobile, and whenever you scroll down and scroll back up on desktop

[7854] Show AFG sub-nav when scrolling up

---

src/components/afg-nav/afg-nav.jsx
src/components/afg-nav/afg-nav.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8430
https://federal-spending-transparency.atlassian.net/browse/DA-8426
Active section on tablet can be closed:
Colors fixed (before/after):
Active section chevron is always larger:

[8430|8426] Tablet sub-nav fixes/make active chevron larger at all times

---

src/components/toc/toc.jsx
src/components/toc/toc.module.scss

https://federal-spending-transparency.atlassian.net/browse/DA-8451
in order to see the flags, add `isNew: true` or `comingSoon: true` as a prop to any of the sections on index.jsx for any page that uses the TOC component (ex. [here](https://github.com/fedspendingtransparency/datalab/blob/dev/src/pages/federal-covid-funding/index.jsx#L53)). in the future, we'll have it based on a date, but for demonstration it can just be true
desktop:
tablet:
mobile:

[8451] TOC New and Coming Soon flags

---

src/pages/index.jsx

To merge the fix into QAT
https://federal-spending-transparency.atlassian.net/browse/DA-8414

8414 - Fixed covid title on homepage

---

src/pages/index.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8601
The sentence with the typo was removed from the MAC, so I updated this branch.

8601 - changed mobile copy for covid feature tile

---

src/page-sections/federal-covid-funding/overview/overview.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8695

8695 - covid section 2 typo

---

src/page-sections/rd-in-contracting/categories/categories.jsx
src/page-sections/rd-in-contracting/spending/spending-chart.jsx
src/pages/rd-in-contracting/index.jsx
src/pages/rd-in-contracting/methodologies.jsx

https://federal-spending-transparency.atlassian.net/browse/DA-8458
I didn't change the paths for the data downloads, because those files haven't been changed yet.
And the copy for the home page tile will be added when we add that tile to the home page.

8458 update rd copy

---

src/pages/rd-in-contracting/index.jsx

No Ticket
ISSUE:  In QAT there are two section #3's in the TOC
FIX:  Removed one

Remove duplicated section #3 from TOC

---

src/components/scrolling-circles/scrolling-circles.jsx

No ticket yet
The check if target exists (in DA-8678) broken the scrolling TOC circles in R&D
Please check scrolling TOC in COVID and R&D
https://user-images.githubusercontent.com/121010/108398931-8d7b8a80-71e7-11eb-81da-9011574a9b51.mov

Fixed check if target exists before it's observed

---

src/pages/rd-in-contracting/index.jsx
src/pages/rd-in-contracting/rd-in-contracting.module.scss

…e grid element for the rd footnotes to xl so the text will be full width at phone and tablet sizes
https://federal-spending-transparency.atlassian.net/browse/DA-8731
The whitespace above the Footnotes component is handled differently in each of the instances of that component. To make them consistent would require changing the css for the StorySection and/or StorySectionHeading, which would affect several pages, as well as small tweaks to the css for each of the pages that already have the Footnotes component. So I just did the quick fix here.

8731 rd footnotes spacing mobile

---

src/page-sections/rd-in-contracting/spending/spending-chart.jsx
src/pages/rd-in-contracting/index.jsx
src/pages/rd-in-contracting/methodologies.jsx

See Slack #dl-rd channel for defects reported by Allie Wallis (items are listed below).  PR contains fixes for items that require code changes (ie. #1, 2, 3, and 5)
https://data-transparency-bfs.slack.com/archives/CJAD4HQBC/p1615409400017900
1. Section 1, last sentence of first paragraph: looks like there is an extra period at the end of the sentence. Quick defect sub-task to fix?
2. Same section, same line, in the MAC, we do not include "analysis" in the hyperlink. Should we just adjust the MAC to reflect QAT?
3. Section 1 Instructions: DOC and VA are listed under Label Definitions in QAT but not in the MAC. Same scenario here, just update MAC? 
4. In the MAC under Viz 2 Instructions Accordion, just need a period added to the end of first bullet point. (Correct in QAT) (not a code …

No ticket yet - R&d copy updates
